Recebe Dados

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
dados = pd.read_excel('/content/drive/MyDrive/DX_LG_Eldorado/DX_alunos.xlsx')

In [ ]:
dados

,Carimbo de data/hora,Nome,Data de Nascimento,Sexo,Cidade Onde Nasceu,Estado Onde Nasceu
0,2023-07-10 10:48:39.921,Luiz,1998-07-20,Masculino,Manaus,Amazonas
1,2023-07-10 10:49:05.991,Douglas da costa cruz,2002-01-26,Masculino,Manaus,Amazonas
2,2023-07-10 10:49:07.151,Lucas Cruz Araújo,2002-11-05,Masculino,Manaus,Amazonas
3,2023-07-10 10:49:11.131,Paulo Vitor Libório Pereira,1998-03-20,Masculino,Itapiranga,Amazonas
4,2023-07-10 10:50:09.205,Isabel Priscila Chaves da Silva Rebello,1998-01-05,Feminino,Manaus,Amazonas
5,2023-07-10 10:52:38.245,Henrique Franklin de Souza,1993-08-17,Masculino,Manaus,Amazonas
6,2023-07-10 10:53:08.576,luccas daniel lira,2001-08-30,Masculino,manaus,amazonas
7,2023-07-10 10:55:02.973,Rodrigo Alencar de Souza,1997-11-15,Masculino,Manaus,Amazonas

Tratamento dos Dados

In [ ]:
dados.columns = ['data_resposta', 'nome', 'data_nascimento', 'sexo', 'cidade_nascimento', 'estado_nascimento']

In [ ]:
dados

,data_resposta,nome,data_nascimento,sexo,cidade_nascimento,estado_nascimento
0,2023-07-10 10:48:39.921,Luiz,1998-07-20,Masculino,Manaus,Amazonas
1,2023-07-10 10:49:05.991,Douglas da costa cruz,2002-01-26,Masculino,Manaus,Amazonas
2,2023-07-10 10:49:07.151,Lucas Cruz Araújo,2002-11-05,Masculino,Manaus,Amazonas
3,2023-07-10 10:49:11.131,Paulo Vitor Libório Pereira,1998-03-20,Masculino,Itapiranga,Amazonas
4,2023-07-10 10:50:09.205,Isabel Priscila Chaves da Silva Rebello,1998-01-05,Feminino,Manaus,Amazonas
5,2023-07-10 10:52:38.245,Henrique Franklin de Souza,1993-08-17,Masculino,Manaus,Amazonas
6,2023-07-10 10:53:08.576,luccas daniel lira,2001-08-30,Masculino,manaus,amazonas
7,2023-07-10 10:55:02.973,Rodrigo Alencar de Souza,1997-11-15,Masculino,Manaus,Amazonas

In [ ]:
nomes_tratados = []
ultimos_nomes = []

for aluno in dados['nome']:
  nome_separado = aluno.split(' ')
  nome_tratado= f'{nome_separado[-1]}, {nome_separado[0]}'
  ultimo_nome = nome_separado[-1]
  nomes_tratados.append(nome_tratado)
  ultimos_nomes.append(ultimo_nome)

nomes_tratados

['Luiz, Luiz',
 'cruz, Douglas',
 'Araújo, Lucas',
 'Pereira, Paulo',
 'Rebello, Isabel',
 'Souza, Henrique',
 'lira, luccas',
 'Souza, Rodrigo']

In [ ]:
ultimos_nomes

['Luiz', 'cruz', 'Araújo', 'Pereira', 'Rebello', 'Souza', 'lira', 'Souza']

In [ ]:
datas_tratadas = []
for data in dados['data_nascimento']:
  data_tratada = data.strftime("%d/%m/%y")
  datas_tratadas.append(data_tratada)

datas_tratadas

['20/07/98',
 '26/01/02',
 '05/11/02',
 '20/03/98',
 '05/01/98',
 '17/08/93',
 '30/08/01',
 '15/11/97']

In [ ]:
dados['nomes_tratados'] = nomes_tratados
dados['ultimos_nomes'] = ultimos_nomes
dados['datas_tratadas'] = datas_tratadas

In [ ]:
dados

,data_resposta,nome,data_nascimento,sexo,cidade_nascimento,estado_nascimento,nomes_tratados,ultimos_nomes,datas_tratadas
0,2023-07-10 10:48:39.921,Luiz,1998-07-20,Masculino,Manaus,Amazonas,"Luiz, Luiz",Luiz,20/07/98
1,2023-07-10 10:49:05.991,Douglas da costa cruz,2002-01-26,Masculino,Manaus,Amazonas,"cruz, Douglas",cruz,26/01/02
2,2023-07-10 10:49:07.151,Lucas Cruz Araújo,2002-11-05,Masculino,Manaus,Amazonas,"Araújo, Lucas",Araújo,05/11/02
3,2023-07-10 10:49:11.131,Paulo Vitor Libório Pereira,1998-03-20,Masculino,Itapiranga,Amazonas,"Pereira, Paulo",Pereira,20/03/98
4,2023-07-10 10:50:09.205,Isabel Priscila Chaves da Silva Rebello,1998-01-05,Feminino,Manaus,Amazonas,"Rebello, Isabel",Rebello,05/01/98
5,2023-07-10 10:52:38.245,Henrique Franklin de Souza,1993-08-17,Masculino,Manaus,Amazonas,"Souza, Henrique",Souza,17/08/93
6,2023-07-10 10:53:08.576,luccas daniel lira,2001-08-30,Masculino,manaus,amazonas,"lira, luccas",lira,30/08/01
7,2023-07-10 10:55:02.973,Rodrigo Alencar de Souza,1997-11-15,Masculino,Manaus,Amazonas,"Souza, Rodrigo",Souza,15/11/97

Saída

In [ ]:
for i in range (len(dados)):
  print('O funcionário {ultimo_nome} nasceu na cidade de {cidade} no estado do {estado} na data de {data}.'.format(ultimo_nome = dados['ultimos_nomes'][i],
                                                                                                                  cidade = dados['cidade_nascimento'][i],
                                                                                                                  estado = dados['estado_nascimento'][i],
                                                                                                                  data = dados['datas_tratadas'][i]))

O funcionário Luiz nasceu na cidade de Manaus no estado do Amazonas na data de 20/07/98.
O funcionário cruz nasceu na cidade de Manaus no estado do Amazonas na data de 26/01/02.
O funcionário Araújo nasceu na cidade de Manaus no estado do Amazonas na data de 05/11/02.
O funcionário Pereira nasceu na cidade de Itapiranga no estado do Amazonas na data de 20/03/98.
O funcionário Rebello nasceu na cidade de Manaus no estado do Amazonas na data de 05/01/98.
O funcionário Souza nasceu na cidade de Manaus no estado do Amazonas na data de 17/08/93.
O funcionário lira nasceu na cidade de manaus no estado do amazonas na data de 30/08/01.
O funcionário Souza nasceu na cidade de Manaus no estado do Amazonas na data de 15/11/97.

Item 3

In [ ]:
#nome, data de nascimento, sexo, cidade onde nasceu, estado aonde nasceu.
funcionarios = ['Ana', 'Bia', 'Pedro', 'João']
datas_nascimento = ['1999-05-25', '1998-06-13', '1996-12-08', '1991-10-18']
lista_sexo = ['Feminino', 'Feminino', 'Masculino', 'Masculino']
cidades_nascimento = ['Manaus', 'Parintins', 'Manaus', 'Manacapuru']
estados_nascimento = ['Amazonas', 'Amazonas', 'Amazonas', 'Amazonas']

In [ ]:
data = {
  'funcionarios' : ['Ana', 'Bia', 'Pedro', 'João'],
  'datas_nascimento' : ['1999-05-25', '1998-06-13', '1996-12-08', '1991-10-18'],
  'lista_sexo' : ['Feminino', 'Feminino', 'Masculino', 'Masculino'],
  'cidades_nascimento' : ['Manaus', 'Parintins', 'Manaus', 'Manacapuru'],
  'estados_nascimento' : ['Amazonas', 'Amazonas', 'Amazonas', 'Amazonas']
}

In [ ]:
# criando um dataframe
data = pd.DataFrame(data)

In [ ]:
data

,funcionarios,datas_nascimento,lista_sexo,cidades_nascimento,estados_nascimento
0,Ana,1999-05-25,Feminino,Manaus,Amazonas
1,Bia,1998-06-13,Feminino,Parintins,Amazonas
2,Pedro,1996-12-08,Masculino,Manaus,Amazonas
3,João,1991-10-18,Masculino,Manacapuru,Amazonas

In [ ]:
funcionarias_feminino = []
funcionarios_masculino = []
for i in range(len(data)):
  if data['lista_sexo'][i]== 'Feminino':
    funcionarias_feminino.append(data['funcionarios'][i])
  else:
    funcionarios_masculino.append(data['funcionarios'][i])

print('Funcionários do sexo feminino')
print(funcionarios_masculino)
print('Funcionários do sexo masculino')
print(funcionarios_masculino)

Funcionários do sexo feminino
['Pedro', 'João']
Funcionários do sexo masculino
['Pedro', 'João']

In [ ]:
lista = data['cidades_nascimento'].tolist()
print(lista)

['Manaus', 'Parintins', 'Manaus', 'Manacapuru']

In [ ]:
data.groupby('cidades_nascimento').count()

,funcionarios,datas_nascimento,lista_sexo,estados_nascimento
cidades_nascimento,,,,
Manacapuru,1,1,1,1
Manaus,2,2,2,2
Parintins,1,1,1,1

In [ ]:
funcionarias_sf = data.loc[data['lista_sexo'] == 'Feminino']
funcionarias_sf

,funcionarios,datas_nascimento,lista_sexo,cidades_nascimento,estados_nascimento
0,Ana,1999-05-25,Feminino,Manaus,Amazonas
1,Bia,1998-06-13,Feminino,Parintins,Amazonas

In [ ]:
funcionarios_sm = data.loc[data['lista_sexo'] == 'Masculino']
funcionarios_sm

,funcionarios,datas_nascimento,lista_sexo,cidades_nascimento,estados_nascimento
2,Pedro,1996-12-08,Masculino,Manaus,Amazonas
3,João,1991-10-18,Masculino,Manacapuru,Amazonas

In [ ]:
funcionarios_cidade = data.loc[data['cidades_nascimento'] == 'Manaus']
funcionarios_cidade

,funcionarios,datas_nascimento,lista_sexo,cidades_nascimento,estados_nascimento
0,Ana,1999-05-25,Feminino,Manaus,Amazonas
2,Pedro,1996-12-08,Masculino,Manaus,Amazonas

In [ ]:
from datetime import datetime as dt

novas_datas = []
for i in range(len(data)):
  nova_data = dt.fromisoformat(data['datas_nascimento'][i])
  nova_data = nova_data.strftime('%y-%m-%d')
  novas_datas.append(nova_data)

print(novas_datas)

In [ ]:
dados_novos = pd.DataFrame({ 'datas_nascimento': novas_datas})
data.update(dados_novos)

In [ ]:
data

In [ ]:
data[data['datas_nascimento'].between('1990-01-01', '1998-12-31')]