In [ ]:
#modulo calculadora.py
def mult (n1, n2):
   return n1 * n2

def soma (n1, n2):
   return n1 + n2

def div (n1, n2):
   if n2 == 0:
      print("Não existe divisão por zero!")
   else:
      return n1/n2

def subt (n1, n2):
   return n1-n2

def pot(n1, n2):
   return n1 ** n2

def converte_binario (numero):
   opcao = int(input("Você quer converter um número para [1]Decimal ou [2]Binário: "))
   if opcao == 1:
      return bin(numero)[2:]
   elif opcao == 2:
      return int(numero, 2)

def raiz (radicando, indice):
   return radicando ** (1/indice)



---



---

####Parte de POO

Funções

In [ ]:
#bibliotecas
import calculadora as cal

In [ ]:
#tratamento de erros
#função para trata dados onde se recebe apenas dados positivos e inteiros
def trata_idade(numero):
  while True:
    try:
      numero = int(numero)
    except:
      numero = input("Número inválido. Digite novamente: ")
    else:
      if numero < 0 or numero > 110:
        numero = input("Número inválido. Digite novamente: ")
      else:
        return numero
        break

In [ ]:
#Digita um texto para receber qualquer dado
def recebe_dado(variavel):
  texto = "Digite " + variavel + ":"
  dado = input(texto)
  return dado

In [ ]:
#Recebe os dados que colocou na função
def recebe_infos():
  nome = recebe_dado("nome")
  idade = recebe_dado("idade")
  altura = recebe_dado("altura")
  peso = recebe_dado("peso")
  return nome, idade, altura, peso

In [ ]:
def cal_imc(peso, altura):
    return cal.div(peso, cal.pot(altura,2))

In [ ]:
class Pessoa():
  def __init__(self, nome, idade, altura, peso):
    #atributos
    self.nome = nome
    self.idade = trata_idade(idade)
    self.altura = altura
    self.peso = peso

  #métodos
  def get_name(self):
    return self.nome

  def get_idade(self):
    return self.idade

  def get_altura(self):
    return self.altura

  def get_peso(self):
    return self.peso

  def imc(self):

    if cal_imc(self.peso, self.altura) < 18.5: status = "Magreza"
    elif cal_imc(self.peso, self.altura) >= 18.5 and cal_imc(self.altura, self.altura) < 25: status = "Normal"
    elif cal_imc(self.peso, self.altura) >= 25 and cal_imc(self.altura, self.altura) < 30: status = "Sobrepeso"
    elif cal_imc(self.peso, self.altura) >= 30 and cal_imc(self.altura, self.altura) < 40: status = "Obesidade"
    elif cal_imc(self.peso, self.altura) >= 40: status = "Obesidade Grave"

    print ("Seu IMC é: {cal_imc:.2f}\nClassificado como {status}.".format(cal_imc = cal_imc(self.peso, self.altura), status = status))

In [ ]:
#usando a função recebe_infos para receber os dados
nome, idade, altura, peso = recebe_infos()
Pessoa_1 = Pessoa(nome, idade, altura, peso)

Digite nome:Isabel
Digite idade:25
Digite altura:1.65
Digite peso:68

In [ ]:
Isabel = Pessoa("Isabel Priscila", -1, 1.65, 68)

Número inválido. Digite novamente: l
Número inválido. Digite novamente: -5
Número inválido. Digite novamente: 2

In [ ]:
Isabel.get_idade()

2

In [ ]:
Isabel.imc()

Seu IMC é: 24.98
Classificado como Normal.



---

Funções do classe Funcionário filha da classe Pessoa

In [ ]:
def converte_pagamento(pagamento):
  dic_moedas = {'Dólar Americano':0.21, 'Euro':0.18, 'Iene Japonês':28.76, 'Dólar Canadense':0.27, 'Peso Argentino':55.13}

  index = 1
  for chave in dic_moedas.items():
   print(f"[{index}] - [{chave}]")
   index += 1
  moeda = int(input("Conforme a lista acima para qual moeda você quer converter seu salario: "))

  index = 1
  for chave, valor in dic_moedas.items():
    if index == moeda:
      print(f"Seu sálario em {chave} é {cal.mult(pagamento, valor):.2f}")
    index += 1

In [ ]:
class Funcionario(Pessoa):
  def __init__(self, nome, idade, altura, peso, horas_trabalho):
    super().__init__(nome, idade, altura, peso)
    self.horas_trabalho = horas_trabalho

  def get_pagamento(self):
    taxa = 21.50

    if idade < 21:
      pagmento = self.horas_trabalho * taxa
    else:
      pagamento = self.horas_trabalho * (taxa + 2.50)

    return pagamento

  def get_bonus(self, pagamento, bonus):
    return cal.soma(pagamento, bonus)

  def get_desconto(self, pagamento, desconto):
    return cal.subt(pagamento, desconto)

  def get_pagamento_convert(self, pagamento):
    return converte_pagamento(pagamento)

In [ ]:
IsabelFunc = Funcionario("Isabel Rebello", 25, 1.65, 68, 40)

In [ ]:
IsabelFunc.get_pagamento_convert(5000)

[1] - [('Dólar Americano', 0.21)]
[2] - [('Euro', 0.18)]
[3] - [('Iene Japonês', 28.76)]
[4] - [('Dólar Canadense', 0.27)]
[5] - [('Peso Argentino', 55.13)]
Conforme a lista acima para qual moeda você quer converter seu salario: 5
Seu sálario em Peso Argentino é 275650.00



---



---

####Parte de importação de arquivos

In [ ]:
#Bibliotecas
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
dados_financial = pd.read_excel('/content/drive/MyDrive/DX_LG_Eldorado/financial_fample_data.xlsx')
dados_financial

,Account,Businees Unit,Currency,Year,Scenario,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
0,Sales,Software,USD,2012,Actuals,90924002.0,82606134.0,72780220.0,52943701.0,77528109.0,96384524.0,77345061.0,98290873.0,79879127.0,95373403.0,54887908.0,82703597.0
1,Cost of Goods Sold,Software,USD,2012,Actuals,-41623278.0,-40464347.0,-30806326.0,-21412962.0,-37047252.0,-44819597.0,-34847393.0,-47903350.0,-35880653.0,-44982115.0,-26929424.0,-34233473.0
2,Commissions Expense,Software,USD,2012,Actuals,-4454359.0,-3386032.0,-3389705.0,-2149257.0,-3168079.0,-4417624.0,-3386461.0,-4052846.0,-3418737.0,-4365527.0,-2455561.0,-3646726.0
3,Payroll Expense,Software,USD,2012,Actuals,-9901680.0,-9871172.0,-8459696.0,-6303408.0,-8493573.0,-11082494.0,-8081033.0,-11070018.0,-8410665.0,-10081727.0,-6300578.0,-9099438.0
4,Travel & Entertainment Expense,Software,USD,2012,Actuals,-951255.0,-838985.0,-872700.0,-624416.0,-919835.0,-1085296.0,-818602.0,-1040585.0,-803190.0,-1158623.0,-611335.0,-941542.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,Travel & Entertainment Expense,Hardware,USD,2023,Forecast,-295046.0,-288819.0,-270521.0,-299399.0,-259557.0,-306337.0,-302042.0,-335932.0,-352326.0,-202497.0,-209741.0,-306375.0
347,R&D Expense,Hardware,USD,2023,Forecast,-1063042.0,-1383994.0,-1005520.0,-1122436.0,-1105967.0,-1152280.0,-1172596.0,-1435420.0,-1381456.0,-865769.0,-855963.0,-1188799.0
348,Consulting Expense,Hardware,USD,2023,Forecast,-1440304.0,-1476449.0,-1202261.0,-1447697.0,-1227951.0,-1255275.0,-1424563.0,-1942571.0,-1593839.0,-1037651.0,-1097675.0,-1397647.0
349,Software/Hardware Expense,Hardware,USD,2023,Forecast,-1825596.0,-1941785.0,-1833335.0,-2389482.0,-1906406.0,-1777976.0,-2005933.0,-2661184.0,-2463031.0,-1455030.0,-1398480.0,-1954771.0
350,Marketing Expense,Hardware,USD,2023,Forecast,-545525.0,-576243.0,-534567.0,-678191.0,-461374.0,-509712.0,-576349.0,-660401.0,-684878.0,-460793.0,-480324.0,-657505.0

In [ ]:
dados_financial.columns = ['account', 'business_unit', 'currency', 'year', 'scenario', 'jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']

In [ ]:
dados_financial

,account,business_unit,currency,year,scenario,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec
0,Sales,Software,USD,2012,Actuals,90924002.0,82606134.0,72780220.0,52943701.0,77528109.0,96384524.0,77345061.0,98290873.0,79879127.0,95373403.0,54887908.0,82703597.0
1,Cost of Goods Sold,Software,USD,2012,Actuals,-41623278.0,-40464347.0,-30806326.0,-21412962.0,-37047252.0,-44819597.0,-34847393.0,-47903350.0,-35880653.0,-44982115.0,-26929424.0,-34233473.0
2,Commissions Expense,Software,USD,2012,Actuals,-4454359.0,-3386032.0,-3389705.0,-2149257.0,-3168079.0,-4417624.0,-3386461.0,-4052846.0,-3418737.0,-4365527.0,-2455561.0,-3646726.0
3,Payroll Expense,Software,USD,2012,Actuals,-9901680.0,-9871172.0,-8459696.0,-6303408.0,-8493573.0,-11082494.0,-8081033.0,-11070018.0,-8410665.0,-10081727.0,-6300578.0,-9099438.0
4,Travel & Entertainment Expense,Software,USD,2012,Actuals,-951255.0,-838985.0,-872700.0,-624416.0,-919835.0,-1085296.0,-818602.0,-1040585.0,-803190.0,-1158623.0,-611335.0,-941542.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,Travel & Entertainment Expense,Hardware,USD,2023,Forecast,-295046.0,-288819.0,-270521.0,-299399.0,-259557.0,-306337.0,-302042.0,-335932.0,-352326.0,-202497.0,-209741.0,-306375.0
347,R&D Expense,Hardware,USD,2023,Forecast,-1063042.0,-1383994.0,-1005520.0,-1122436.0,-1105967.0,-1152280.0,-1172596.0,-1435420.0,-1381456.0,-865769.0,-855963.0,-1188799.0
348,Consulting Expense,Hardware,USD,2023,Forecast,-1440304.0,-1476449.0,-1202261.0,-1447697.0,-1227951.0,-1255275.0,-1424563.0,-1942571.0,-1593839.0,-1037651.0,-1097675.0,-1397647.0
349,Software/Hardware Expense,Hardware,USD,2023,Forecast,-1825596.0,-1941785.0,-1833335.0,-2389482.0,-1906406.0,-1777976.0,-2005933.0,-2661184.0,-2463031.0,-1455030.0,-1398480.0,-1954771.0
350,Marketing Expense,Hardware,USD,2023,Forecast,-545525.0,-576243.0,-534567.0,-678191.0,-461374.0,-509712.0,-576349.0,-660401.0,-684878.0,-460793.0,-480324.0,-657505.0

In [ ]:
months = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']
dados_financial[months[0]][0]

90924002.0

In [ ]:
months = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']
year_month = []; scenarios = []; currencys = []; values = []

for line in range(len(dados_financial)):
  for month in range(len(months)):

    line_year_month = months[month]
    year = dados_financial['year'][line]
    scenario = dados_financial['scenario'][line]
    currency = dados_financial['currency'][line]
    value = dados_financial[months[month]][line]

    year_month.append(line_year_month)
    scenarios.append(scenario)
    currencys.append(currency)
    values.append(value)

In [ ]:
data = {'year_month' : year_month,'scenario': scenarios, 'currency': currencys, 'values' : values}
dados_spending_account = pd.DataFrame(data)
dados_spending_account

     year_month  scenario currency      values
0      jan_2012   Actuals      USD  90924002.0
1      feb_2012   Actuals      USD  82606134.0
2      mar_2012   Actuals      USD  72780220.0
3      apr_2012   Actuals      USD  52943701.0
4      may_2012   Actuals      USD  77528109.0
...         ...       ...      ...         ...
4207   aug_2023  Forecast      USD   -660401.0
4208   sep_2023  Forecast      USD   -684878.0
4209   oct_2023  Forecast      USD   -460793.0
4210   nov_2023  Forecast      USD   -480324.0
4211   dec_2023  Forecast      USD   -657505.0

[4212 rows x 4 columns]

In [ ]:
set_scenario = set(dados_financial['Scenario'])
set_scenario

{'Actuals', 'Budget', 'Forecast'}

####Investigando os dados
Class BusinessUnit
- Account

Class SpendingAccount (BusinessUnit)
- month_year
- scenario
- currency
- value

**Transformando em objeto**

In [ ]:
class BusinessUnit():
  def __init__(self, account="", businees_unit="", currency=""):
    self.account = account

  def get_account(self):
    return self.account

In [ ]:
class SpendingAccount():
  def __init__(self, month="", year="", scenario="", currency="", value=""):
    self.month = month
    self.year = year
    self.scenario = scenario
    self.currency = currency
    self.value = value

  def get_month(self):
    return self.month

  def get_year(self):
    return self.year

  def get_scenario(self):
    return self.scenario

  def get_currency(self):
    return self.currency

  def get_value(self):
    return self.value

In [ ]:
months = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']
objetos = []

for line in range(len(dados_financial)):
  for month in range(len(months)):

    line_month = months[month]
    year = dados_financial['year'][line]
    scenario = dados_financial['scenario'][line]
    currency = dados_financial['currency'][line]
    value = dados_financial[months[month]][line]

    objeto = SpendingAccount(line_month, year, scenario, currency, value)

    objetos.append(objeto)

In [ ]:
objetos[1].get_year()

2012

In [ ]:
dados_employee = pd.read_excel('/content/drive/MyDrive/DX_LG_Eldorado/employee_sample_data.xlsx')
dados_employee

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,NaT
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,NaT
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,E03094,Wesley Young,Sr. Analyst,Marketing,Speciality Products,Male,Caucasian,33,2016-09-18,98427,0.00,United States,Columbus,NaT
996,E01909,Lillian Khan,Analyst,Finance,Speciality Products,Female,Asian,44,2010-05-31,47387,0.00,China,Chengdu,2018-01-08
997,E04398,Oliver Yang,Director,Marketing,Speciality Products,Male,Asian,31,2019-06-10,176710,0.15,United States,Miami,NaT
998,E02521,Lily Nguyen,Sr. Analyst,Finance,Speciality Products,Female,Asian,33,2012-01-28,95960,0.00,China,Chengdu,NaT
999,E03545,Sofia Cheng,Vice President,Accounting,Corporate,Female,Asian,63,2020-07-26,216195,0.31,United States,Miami,NaT

In [ ]:
type(dados_employee)

pandas.core.frame.DataFrame